# Generated by Django 4.1.7 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gained_xp",
            field=models.IntegerField(default=0),
        ),
    ]
